### ISSUE TITLE
文件缺失

### ISSUE THREAD

**Issue by Fzy-k** [CJReinforce/JOWA#1]
大佬，能提供一下fine_tune里提到的npy文件吗

**Comment by CJReinforce** [comment]
Thank you very much for your interest. We apologize that our code is still being optimized. We will finish all the open source work, including the optimized training code (which has merged the pre-training and fine-tuning code), and the fine-tuning dataset **by the end of the month**. We hope you will understand.

**Comment by CJReinforce** [comment]
Currently, we have open-sourced the [fine-tuning dataset](https://github.com/CJReinforce/JOWA/blob/main/fine_tuning_dataset.zip). The dataset contains three data qualities: expert, suboptimal, and highly-suboptimal, which are uniformly sampled from the last 20%, all, and first 20% of the [complete dataset](https://console.cloud.google.com/storage/browser/atari-replay-datasets), respectively. For downloading our dataset and fine-tuning commands, see [here](https://github.com/CJReinforce/JOWA?tab=readme-ov-file#fine-tuning).
